spring:
  profiles:
    group:
      "local": "localdb,common"
      "prod": "proddb,common"

---

spring:
  config:
    activate:
      on-profile: localdb
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
  redis:
    host: localhost
    port: 6300

---

spring:
  config:
    activate:
      on-profile: proddb
  datasource:
    url: jdbc:mysql://momo-database.c68ioe4k3nu7.ap-northeast-2.rds.amazonaws.com:3306/momo
    username: admin
    password: ahenahdu
  redis:
    host: momo.oc76gu.0001.apn2.cache.amazonaws.com
    port: 6379

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://www.seoultaste.click/users/kakao/callback
            authorization-grant-type: authorization_code
            client-id: 2adbf21838760b4e80d709eeb37a8857
            scope: profile_nickname,account_email
            client-name: Kakao
            client-authentication-method: POST
        provider:
          kakao:
            account-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            account-info-uri: https://kapi.kakao.com/v2/account/me
            token-uri: https://kauth.kakao.com/oauth/token
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

jwt:
  header: Authorization
  refresh-token-validity-in-seconds: '3600'
  access-token-validity-in-seconds: '3600'
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

cloud:
  aws:
    s3:
      bucket: team6-bucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIAT3XOGPI7YU4ZCKE2
      secretKey: 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
    stack:
      auto: 'false'

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace